apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-sample
  namespace: devops-sample
  labels:
    app: devops-sample
spec:
  replicas: 3
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: devops-sample
  strategy:
    rollingUpdate:
      maxSurge: 1 # as an absolute number of replicas
      maxUnavailable: 33% # as % of replicas
    type: RollingUpdate
  minReadySeconds: 5 # Using minReadySeconds to add a readiness buffer.
  template:
    metadata:
      labels:
        app: devops-sample
    spec:
      containers:
        - name: devops-sample
          image: devops-sample:0.0.5-SNAPSHOT
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30
            failureThreshold: 2
          livenessProbe:
              httpGet:
                path: /actuator/health/liveness # Default path; adjust as necessary for your application's health check.
                port: 8080
              initialDelaySeconds: 15
              failureThreshold: 2
              periodSeconds: 45
          env:
            - name: PORT
              value: "8080"
          resources:
            limits:
              cpu: "1"
              memory: "300Mi"
            requests:
              cpu: "100m"
              memory: "100Mi"
