apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-sample
  namespace: devops-sample
  labels:
    app: devops-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-sample
  template:
    metadata:
      labels:
        app: devops-sample
    spec:
      containers:
        - name: devops-sample
          image: devops-sample
          env:
            - name: PORT
              value: "8080"