apiVersion: v1
kind: Service
metadata:
  name: devops-sample
  namespace: devops-sample
  labels:
    app: devops-sample
spec:
  ports:
    - port: 8080
      protocol: TCP
  clusterIP: None
  selector:
    app: devops-sample