apiVersion: v1
kind: Service
metadata:
  name: devops-sample
  namespace: devops-sample
  labels:
    app: devops-sample
spec:
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30080
  selector:
    app: devops-sample